MONITORED_CHANNEL_IDS = [ 1019446913268973689, 1007196545600458794, 954916843775225916, 1148761026909700216,]
SCAN_LIMIT_BYTES = 104857600
TRUSTED_UIDS = [ 444257402007846942 ]
PERSONALITY = "eiki"
LANGUAGE = "normal"
TOKEN = "SaGuYaIzaYOI"
GUESS = "❔"
METADATA = "🔎"
DELETE_DM = "❌"
GRADIO_BACKEND = "https://yoinked-da-nsfw-checker.hf.space/"

CHATBOT_RESPONSIVE = [ 1019446913268973689 ]
CHATBOT_ENABLE_VISION = true

USE_GEMINIAPI = false
GEMINIAPI_TOKEN = "onceTheSeaTurnsToBlood"
GEMINIAPI_MODEL = "gemini-2.0-flash"

USE_OPENROUTER = true
OPENROUTER_TOKEN = "theWorldLookedSoDifferentIsnTIt"
OPENROUTER_MODEL = "openrouter/horizon-alpha"